version: '3.4'

services:
  soccerDb:
    container_name: soccerDb
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: soccer
      ME_CONFIG_BASICAUTH_PASSWORD: Soccer2021!
    restart: always
    ports: 
        - "27017:27017"
    volumes: 
        - mongo_data:/data/db 

  soccerApi:
    container_name: soccerApi
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "DatabaseSettings:ConnectionString=mongodb://soccerDb:27017"
    depends_on: 
      - soccerDb
    ports:
      - 5000:5000

