version: '3.4'

services:
  soccerDb:
    container_name: soccerDb
    restart: always
    ports: 
        - "26717:27017"
    volumes: 
        - mongo_data:/data/db 

  soccerApi:
    container_name: soccerApi
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "DatabaseSettings:ConnectionString=mongodb://soccerDb:20717"
    depends_on: 
      - soccerDb
    ports:
      - 5000:5000

